//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public System.DateTime User_DateOfBirth { get; set; }
        public string User_Place { get; set; }
        public string User_Job { get; set; }
    }
}
